# Jekyll Resume Theme

# Site settings
title: Awale Sushil
email: mail at sushilawale dot com
description: Portfolio of Sushil Awale
baseurl: ""
url: "https://sushilawale.com"
name: Sushil Awale
job: Natural Language Processing Research Intern
location: Patan, Nepal
twitter: sushilawale
github:  awalesushil
blog: https://blog.sushilawale.com
linkedin: sushilawale

# Build settings
markdown: kramdown
